# Generated by Django 6.0.5 on 2026-06-01 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('text_it', models.CharField(max_length=160)),
                ('translation_pt', models.CharField(max_length=180)),
                ('verb', models.CharField(blank=True, max_length=60)),
                ('present_example', models.CharField(blank=True, max_length=180)),
                ('past_example', models.CharField(blank=True, max_length=180)),
                ('future_example', models.CharField(blank=True, max_length=180)),
                ('context_note', models.CharField(blank=True, max_length=180)),
                ('source_paragraph', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.FloatField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_grade', models.CharField(blank=True, max_length=12)),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='study.segment')),
            ],
            options={
                'ordering': ['segment__position'],
            },
        ),
    ]
