# Generated by Django 6.0.5 on 2026-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_reviewstate_user_alter_reviewstate_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstate',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
