from django.core.management.base import BaseCommand

from study.models import Segment


CARDS = [
    {
        "position": 1,
        "text_it": "Alice moriva di noia",
        "translation_pt": "Alice morria de tédio",
        "verb": "morire",
        "present_example": "Alice muore di noia.",
        "past_example": "Alice moriva di noia.",
        "future_example": "Alice morirà di noia.",
        "source_paragraph": 1,
    },
    {
        "position": 2,
        "text_it": "a starsene seduta",
        "translation_pt": "por ficar sentada",
        "verb": "stare",
        "present_example": "Alice sta seduta.",
        "past_example": "Alice stava seduta.",
        "future_example": "Alice starà seduta.",
        "source_paragraph": 1,
    },
    {
        "position": 3,
        "text_it": "con la sorella",
        "translation_pt": "com a irmã",
        "source_paragraph": 1,
    },
    {
        "position": 4,
        "text_it": "sulla proda",
        "translation_pt": "na margem",
        "context_note": "Proda: margem ou beira.",
        "source_paragraph": 1,
    },
    {
        "position": 5,
        "text_it": "senza far niente",
        "translation_pt": "sem fazer nada",
        "verb": "fare",
        "present_example": "Non fa niente.",
        "past_example": "Non faceva niente.",
        "future_example": "Non farà niente.",
        "source_paragraph": 1,
    },
    {
        "position": 6,
        "text_it": "aveva sbirciato",
        "translation_pt": "tinha espiado",
        "verb": "sbirciare",
        "present_example": "Alice sbircia il libro.",
        "past_example": "Alice aveva sbirciato.",
        "future_example": "Alice sbircerà il libro.",
        "source_paragraph": 1,
    },
    {
        "position": 7,
        "text_it": "un paio di volte",
        "translation_pt": "algumas vezes",
        "source_paragraph": 1,
    },
    {
        "position": 8,
        "text_it": "il libro",
        "translation_pt": "o livro",
        "source_paragraph": 1,
    },
    {
        "position": 9,
        "text_it": "che la sorella",
        "translation_pt": "que a irmã",
        "source_paragraph": 1,
    },
    {
        "position": 10,
        "text_it": "stava leggendo",
        "translation_pt": "estava lendo",
        "verb": "leggere",
        "present_example": "Lei legge.",
        "past_example": "Lei stava leggendo.",
        "future_example": "Lei leggerà.",
        "source_paragraph": 1,
    },
    {
        "position": 11,
        "text_it": "ma non c'erano figure",
        "translation_pt": "mas não havia figuras",
        "verb": "esserci",
        "present_example": "Ci sono figure.",
        "past_example": "C'erano figure.",
        "future_example": "Ci saranno figure.",
        "source_paragraph": 1,
    },
    {
        "position": 12,
        "text_it": "né dialoghi",
        "translation_pt": "nem diálogos",
        "source_paragraph": 1,
    },
    {
        "position": 13,
        "text_it": "e a cosa serve",
        "translation_pt": "e para que serve",
        "verb": "servire",
        "present_example": "A cosa serve?",
        "past_example": "A cosa serviva?",
        "future_example": "A cosa servirà?",
        "source_paragraph": 1,
    },
    {
        "position": 14,
        "text_it": "un libro",
        "translation_pt": "um livro",
        "source_paragraph": 1,
    },
    {
        "position": 15,
        "text_it": "pensava Alice",
        "translation_pt": "pensava Alice",
        "verb": "pensare",
        "present_example": "Alice pensa.",
        "past_example": "Alice pensava.",
        "future_example": "Alice penserà.",
        "source_paragraph": 1,
    },
    {
        "position": 16,
        "text_it": "senza figure né dialoghi",
        "translation_pt": "sem figuras nem diálogos",
        "source_paragraph": 1,
    },
    {
        "position": 17,
        "text_it": "Stava dunque calcolando",
        "translation_pt": "Então estava calculando",
        "verb": "calcolare",
        "present_example": "Alice calcola.",
        "past_example": "Alice stava calcolando.",
        "future_example": "Alice calcolerà.",
        "source_paragraph": 2,
    },
    {
        "position": 18,
        "text_it": "fra sé e sé",
        "translation_pt": "consigo mesma",
        "source_paragraph": 2,
    },
    {
        "position": 19,
        "text_it": "se il piacere",
        "translation_pt": "se o prazer",
        "source_paragraph": 2,
    },
    {
        "position": 20,
        "text_it": "di farsi una collana",
        "translation_pt": "de fazer um colar",
        "verb": "farsi",
        "present_example": "Si fa una collana.",
        "past_example": "Si faceva una collana.",
        "future_example": "Si farà una collana.",
        "source_paragraph": 2,
    },
    {
        "position": 21,
        "text_it": "di margherite",
        "translation_pt": "de margaridas",
        "source_paragraph": 2,
    },
    {
        "position": 22,
        "text_it": "fosse valsa la fatica",
        "translation_pt": "valesse o esforço",
        "verb": "valere",
        "present_example": "Vale la fatica.",
        "past_example": "Valeva la fatica.",
        "future_example": "Varrà la fatica.",
        "source_paragraph": 2,
    },
    {
        "position": 23,
        "text_it": "di tirarsi in piedi",
        "translation_pt": "de se levantar",
        "verb": "tirarsi",
        "present_example": "Si tira in piedi.",
        "past_example": "Si tirava in piedi.",
        "future_example": "Si tirerà in piedi.",
        "source_paragraph": 2,
    },
    {
        "position": 24,
        "text_it": "per andare a raccogliere",
        "translation_pt": "para ir colher",
        "verb": "andare",
        "present_example": "Va a raccogliere.",
        "past_example": "Andava a raccogliere.",
        "future_example": "Andrà a raccogliere.",
        "source_paragraph": 2,
    },
    {
        "position": 25,
        "text_it": "le margherite",
        "translation_pt": "as margaridas",
        "source_paragraph": 2,
    },
    {
        "position": 26,
        "text_it": "quando d'improvviso",
        "translation_pt": "quando de repente",
        "source_paragraph": 2,
    },
    {
        "position": 27,
        "text_it": "le sfrecciò accanto",
        "translation_pt": "passou veloz ao lado dela",
        "verb": "sfrecciare",
        "present_example": "Il coniglio sfreccia.",
        "past_example": "Il coniglio sfrecciò.",
        "future_example": "Il coniglio sfreccerà.",
        "source_paragraph": 2,
    },
    {
        "position": 28,
        "text_it": "un coniglio bianco",
        "translation_pt": "um coelho branco",
        "source_paragraph": 2,
    },
    {
        "position": 29,
        "text_it": "dagli occhi rosa",
        "translation_pt": "de olhos cor-de-rosa",
        "source_paragraph": 2,
    },
    {
        "position": 30,
        "text_it": "Non c'era troppo",
        "translation_pt": "Não havia muito",
        "verb": "esserci",
        "present_example": "Non c'è troppo.",
        "past_example": "Non c'era troppo.",
        "future_example": "Non ci sarà troppo.",
        "source_paragraph": 3,
    },
    {
        "position": 31,
        "text_it": "da meravigliarsi",
        "translation_pt": "para se admirar",
        "verb": "meravigliarsi",
        "present_example": "Alice si meraviglia.",
        "past_example": "Alice si meravigliò.",
        "future_example": "Alice si meraviglierà.",
        "source_paragraph": 3,
    },
    {
        "position": 32,
        "text_it": "Alice trovò",
        "translation_pt": "Alice achou",
        "verb": "trovare",
        "present_example": "Alice trova.",
        "past_example": "Alice trovò.",
        "future_example": "Alice troverà.",
        "source_paragraph": 3,
    },
    {
        "position": 33,
        "text_it": "troppo stravagante",
        "translation_pt": "muito estranho",
        "source_paragraph": 3,
    },
    {
        "position": 34,
        "text_it": "sentire il Coniglio",
        "translation_pt": "ouvir o Coelho",
        "verb": "sentire",
        "present_example": "Alice sente il Coniglio.",
        "past_example": "Alice sentì il Coniglio.",
        "future_example": "Alice sentirà il Coniglio.",
        "source_paragraph": 3,
    },
    {
        "position": 35,
        "text_it": "Farò tardi",
        "translation_pt": "Vou me atrasar",
        "verb": "fare",
        "present_example": "Faccio tardi.",
        "past_example": "Ho fatto tardi.",
        "future_example": "Farò tardi.",
        "source_paragraph": 3,
    },
    {
        "position": 36,
        "text_it": "troppo tardi",
        "translation_pt": "muito tarde",
        "source_paragraph": 3,
    },
    {
        "position": 37,
        "text_it": "capì che",
        "translation_pt": "entendeu que",
        "verb": "capire",
        "present_example": "Alice capisce.",
        "past_example": "Alice capì.",
        "future_example": "Alice capirà.",
        "source_paragraph": 3,
    },
    {
        "position": 38,
        "text_it": "tutto le parve",
        "translation_pt": "tudo lhe pareceu",
        "verb": "parere",
        "present_example": "Tutto le pare naturale.",
        "past_example": "Tutto le parve naturale.",
        "future_example": "Tutto le parrà naturale.",
        "source_paragraph": 3,
    },
    {
        "position": 39,
        "text_it": "perfettamente naturale",
        "translation_pt": "perfeitamente natural",
        "source_paragraph": 3,
    },
    {
        "position": 40,
        "text_it": "quando vide il Coniglio",
        "translation_pt": "quando viu o Coelho",
        "verb": "vedere",
        "present_example": "Alice vede il Coniglio.",
        "past_example": "Alice vide il Coniglio.",
        "future_example": "Alice vedrà il Coniglio.",
        "source_paragraph": 3,
    },
]


class Command(BaseCommand):
    help = "Cria o primeiro lote de cards do Capítulo I."

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for card in CARDS:
            segment, was_created = Segment.objects.update_or_create(
                position=card["position"],
                defaults={"chapter": 1, **card},
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Cards carregados: {created} criados, {updated} atualizados."
            )
        )
